Add asynchronous
ruby-web/chatspace pull request #7
Opened 2019-03-03 02:02 UTC by ruby-web

2019-03-03 02:07 UTC, ruby-web commented
##WHAT
メッセージ送信機能を非同期通信化した。
##WHY
更新しなくてもメッセージを送信できるようにするため。

2019-03-03 02:17 UTC, yuki-uchida requested changes

2019-03-03 02:17 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +  function buildHTML(message){
buildHTMLでは、何をどうするのかがわかりづらいので、buildSendMessageHTMLとかいかがでしょうか

2019-03-03 02:17 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +      var html = buildHTML(data);
dataでは、何を受け取ったのかわからないので、それがわかる名前に変えましょう

2019-03-03 02:17 UTC, yuki-uchida commented on app/controllers/messages_controller.rb
> +      # redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'
これ失敗した時の処理無さそうに見えます。

2019-03-04 00:46 UTC, ruby-web commented on app/assets/javascripts/message.js
> +  function buildHTML(message){
修正しました。

2019-03-04 00:46 UTC, ruby-web commented on app/assets/javascripts/message.js
> +      var html = buildHTML(data);
修正しました。

2019-03-04 01:07 UTC, ruby-web commented on app/controllers/messages_controller.rb
> +      # redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'
修正しました。

2019-03-04 02:04 UTC, hzak2xx approved these changes
LGTM

2019-03-04 02:26 UTC, merged